version: '3'

services:
  pyproxy:
    image: python:3
    command: python3 /app/app.py
    ports:
      - "8080:8080"
    volumes:
      - pyproxy-data:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        
networks:
  bridge-network:
    driver: bridge
        
volumes:
  pyproxy-data:
    driver: local