version: '3'

services:
  pyproxy:
    build: .
    image: pyproxy:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - pyproxy-data:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - bridge
        
volumes:
  pyproxy-data:
    driver: local

networks:
  bridge:
    driver: bridge
