version: '3'

services:
  app:
    build: .
    image: my-app:latest
    ports:
      - "8080:8080"
    volumes:
      - myapp-data:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - bridge
        
volumes:
  myapp-data:
    driver: local

networks:
  bridge:
    driver: bridge
